### ISSUE TITLE
Feature request: son-publish list, download?

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-cli#117]
I was wondering if there is any possibility in son-cli to list and download VNFDs etc. which have been uploaded to the SDK catalogue?

Sure, we can show the mongo db in the demo, but shouldn't there be the possibility to fetch artifacts from the catalogue (except of the automated download in son-package)?

**Comment by lconceicao** [comment]
@mpeuster I agree that the developer should have the possibility to list and download artifacts from the catalogue. My doubt is if this functionality should be included in son-publish or create a separate tool for this purpose instead.
What do you think?

**Comment by mpeuster** [comment]
@lconceicao Right, would be strange to have it in a tool called `son-publish`. We should keep it in mind for one of the next WP3 telcos :-)

**Comment by lconceicao** [comment]
It's been established that this functionality will be available in the new son-access tool. Closing issue.
