### ISSUE TITLE
son-profile: Automated measurements

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-cli#127]
Automatically start and configure son-monitor for each profiling run.

**Comment by stevenvanrossem** [comment]
done by: https://github.com/sonata-nfv/son-cli/pull/164
will still add some documentation how to use it...

**Comment by stevenvanrossem** [comment]
documentation added here:
https://github.com/sonata-nfv/son-cli/wiki/son-profile-automated-testing
