### ISSUE TITLE
son-profile: First end-to-end prototype

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-cli#128]
Feature: Simple automated measurements of example services.

**Comment by stevenvanrossem** [comment]
done by: https://github.com/sonata-nfv/son-cli/pull/164
will still add some documentation how to use it...

**Comment by stevenvanrossem** [comment]
documentation added here:
https://github.com/sonata-nfv/son-cli/wiki/son-profile-automated-testing
