### ISSUE TITLE
son-profile: Merge SAP concepts used by Steven with PED/MP concepts used by Manuel

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-cli#139]
Clear separation:

SAP/MP configuration in PED file
Measurements / monitoring configurations in son-monitor descriptor

**Comment by stevenvanrossem** [comment]
done by: https://github.com/sonata-nfv/son-cli/pull/164
will still add some documentation which fields in the  PED file are needed for this

**Comment by stevenvanrossem** [comment]
documentation started here:
https://github.com/sonata-nfv/son-cli/wiki/son-profile-automated-testing
