### ISSUE TITLE
Integration test 2 is failing

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-cli#156]
Hello, the integration test 2 have the following error:

10:09:12 2017-01-17 09:09:11 jclouds-sdk-private-ece son.package.package[19988] ERROR Unable to solve all dependencies required by the service descriptor.

10:09:12 2017-01-17 09:09:11 jclouds-sdk-private-ece son.package.package[19988] ERROR Failed to package function descriptors

10:09:12 2017-01-17 09:09:11 jclouds-sdk-private-ece son.package.package[19988] ERROR Failed to package Package Content Section. Could not find a network service and/or its referenced function descriptors

10:09:12 2017-01-17 09:09:11 jclouds-sdk-private-ece son.package.package[19988] CRITICAL Missing package descriptor. Failed to generate package.

More information:
https://jenkins.sonata-nfv.eu/view/INTEGRATION/job/int-2-sdk-workflow/330/console

**Comment by lconceicao** [comment]
Hello @felipevicens,

I'm on top of this. We removed the sdk catalogues from son-package and we are also changing the integration tests accordingly.

**Comment by lconceicao** [comment]
Done. Removed integration tests with SDK catalogues, tests are no longer failing.
Next step is to develop integration tests with son-access to communicate with GTKeeper to solve external dependencies (descriptors).
