### ISSUE TITLE
son-package: project version in project.yml

### ISSUE THREAD

**Issue by elekjani** [sonata-nfv/son-cli#168]
The version string "0.4" is hardcoded in the son.workspace.project.Project class and for any project that has a different version than that an error is raised and no package is generated. As the catalogue identify the packages based on the (name, vendor, version) triple one cannot upload a package with different version (as it cannot be created with son-package).

**Comment by lconceicao** [comment]
The problem is solved. @elekjani, thanks for your contribution.
