### ISSUE TITLE
Feature: Package signing

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-cli#177]
This new feature will enable Package signing in the `son-access` component.
This feature should be switchable. User could set an option to activate/deactivate package signing.

The `son-access` component will read user's settings from `son-workspace` to load the user's private key, public key, and an optional certificate.
If the keys and certificate are not provided by the user, then `son-access` will generate and store them in the location configured in `son-workspace` settings.

Before `POST` of the package, `son-access` will sign the package using the user's private key (Kpr).
Then, the HTTP `POST` request will include the original package, signed package hash, user's public key (Kpb) and the certificate (optional):

 `Payload`: `son-package` + `signed son-package` + `Kpb` + `certificate` (optional) 

Milestone Y3B (F2F Paris)
Related issue: son-gkeeper #342

**Comment by lconceicao** [comment]
@dang03 is this completed?

**Comment by jbonnet** [comment]
@lconceicao, @dang03 
Since the most recent GK's API PR (son-gkeeper#710) the `signature` (optional) field coming in the package on-boarding request is being passed to the `son-validate` (`''` if not present).

**Comment by dang03** [comment]
@lconceicao Yes, the feature is completed.
What is currently pending is to test the integration end-to-end from son-cli to the Catalogue using the digital signature feature now that the GK API supports it.
