### ISSUE TITLE
[5GTANGO] Re-factor packaging tool as REST service

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-cli#264]
In 5GTANGO we will have a packaging micro service that can by accessed by REST.

Features:
* package uploaded files
* unpackage and present files for download

**Comment by tsbatista** [comment]
You might want to create a 5GTANGO fork for that, as that is out off the scope of the work of SONATA

**Comment by mpeuster** [comment]
It is, we just needed this issue to demonstrate the new guys how the issue system will work :-) 

The decision by the project lead was to not go for a fork solution but to have the TANGO developments in separated branches of the repo. To keep the "SONATA" brand.
