### ISSUE TITLE
 503  Service Unavailable    (repo.sonata-nfv.eu)

### ISSUE THREAD

**Issue by Kernelalive** [sonata-nfv/son-cli#265]
Hello all,
Sonatas repo seems to be down.I get the same error two days now.

Err:6 http://repo.sonata-nfv.eu ubuntu-xenial Release                    
  503  Service Unavailable
Err:7 http://repo.sonata-nfv.eu ubuntu-trusty Release                    
  503  Service Unavailable

**Comment by mpeuster** [comment]
@felipevicens can you help here?

**Comment by felipevicens** [comment]
@Kernelalive can you try again?

**Comment by Kernelalive** [comment]
Everything works perfect!
Thanks mate!Cheers
