### ISSUE TITLE
son-push should check the HTTP response code

### ISSUE THREAD

**Issue by lconceicao** [sonata-nfv/son-cli#98]
Upon pushing a package to the GK, son-push must check the response code and trigger and error for codes different than 200.

**Comment by Jmanuel4SandMan** [comment]
Small addition: if a connection fails, son-push will crash with
```
return "Service package upload failed. " + e
TypeError: Can't convert 'ConnectionError' object to str implicitly
```

**Comment by lconceicao** [comment]
`son-push` functionality will be included in the new tool `son-access`. The code will probability be re-written, so this issue is no longer relevant in this context.
